[project]
name = "blackrl"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.14"
dependencies = [
    "codon-jit>=0.4.3",
    "cookiecutter-data-science>=2.3.0",
    "ruff>=0.14.1",
]
